@baseUrl = http://localhost:3333
@userId = cmcv7vxcp0000sdq0mn3qn0bq

# @name Create_user
POST {{baseUrl}}/api/v1/register
Content-Type: application/json

{
    "name":"Richard Lirio",
    "email": "richard2@hotmail.com",
    "password": "123456"
}

###

# @name Authenticate
POST {{baseUrl}}/api/v1/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin123"
}

###

# @name Logout
POST {{baseUrl}}/api/v1/logout


###

# @name Fetch_all_users
GET {{baseUrl}}/api/v1/users
Content-Type: application/json

###


# @name Get_user_by_id
GET {{baseUrl}}/api/v1/users/{{userId}}
Content-Type: application/json

###


# @name Delete_user_by_id
DELETE {{baseUrl}}/api/v1/users/{{userId}}
Content-Type: application/json

###